### ISSUE TITLE
'MaskFormer' object has no attribute 'module'

### ISSUE THREAD

**Issue by wendyhuang2021** [clovaai/ECLIPSE#3]
Hi! I got a error below: `'MaskFormer' object has no attribute 'module'` and tried the weights from self-training step0 and which download from your page.
Do you know what's wrong is it? Or this is a version problem? 
(Sorry I asked your version problem in the previous issue, but the cost for changing cuda version is too heavy to me.)

in [train_inc.py L140](https://github.com/clovaai/ECLIPSE/blob/963d9f6287f132b97d56594d43482a94e86dd439/train_inc.py#L140)
```
if self.cfg.CONT.NUM_PROMPTS > 0:
    self.model.module.copy_prompt_embed_weights()# error occur
    self.model.module.copy_mask_embed_weights()
    self.model.module.copy_no_obj_weights()
    self.model.module.copy_prompt_trans_decoder_weights()
```

ERROR message
```
[05/03 17:47:44 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from results/ade_ss_100_step0.pth ...
[05/03 17:47:44 fvcore.common.checkpoint]: [Checkpointer] Loading from results/ade_ss_100_step0.pth ...
WARNING [05/03 17:47:44 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
sem_seg_head.predictor.class_embed.cls.2.layers.0.{bias, weight}
sem_seg_head.predictor.class_embed.cls.2.layers.1.{bias, weight}
sem_seg_head.predictor.class_embed.cls.2.layers.2.{bias, weight}
sem_seg_head.predictor.prompt_embed.0.0.weight
sem_seg_head.predictor.prompt_embed.0.1.weight
sem_seg_head.predictor.prompt_embed.0.2.weight
sem_seg_head.predictor.prompt_embed.0.3.weight
sem_seg_head.predictor.prompt_embed.0.4.weight
sem_seg_head.predictor.prompt_embed.0.5.weight
sem_seg_head.predictor.prompt_embed.0.6.weight
sem_seg_head.predictor.prompt_embed.0.7.weight
sem_seg_head.predictor.prompt_embed.0.8.weight
sem_seg_head.predictor.prompt_feat.0.weight
sem_seg_head.predictor.prompt_mask_embed.0.layers.0.{bias, weight}
sem_seg_head.predictor.prompt_mask_embed.0.layers.1.{bias, weight}
sem_seg_head.predictor.prompt_mask_embed.0.layers.2.{bias, weight}
Traceback (most recent call last):
  File "train_inc.py", line 782, in <module>
    launch(
  File "/home/vllab/anaconda3/envs/mask2former/lib/python3.8/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_inc.py", line 772, in main
    trainer.resume_or_load(resume=args.resume)
  File "train_inc.py", line 140, in resume_or_load
    self.model.module.copy_prompt_embed_weights()
  File "/home/vllab/anaconda3/envs/mask2former/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
```

**Comment by zhengyuan-xie** [comment]
Hi, I also got this error. Do you use a single GPU? I think when a single GPU is used, the DDP training process won't be launched, so I simply change the corresponding code to:
```
if hasattr(self.model, "module"):
    self.model.module.copy_prompt_embed_weights()
    self.model.module.copy_mask_embed_weights()
    self.model.module.copy_no_obj_weights()
    self.model.module.copy_prompt_trans_decoder_weights() 
else: 
    self.model.copy_prompt_embed_weights()
    self.model.copy_mask_embed_weights()
    self.model.copy_no_obj_weights()
    self.model.copy_prompt_trans_decoder_weights() 
```
However, I got another error: `RuntimeError: Global alloc not supported yet`, one solution is replacing `batch_dice_loss_jit` with `batch_dice_loss` but I'm not sure whether it is correct.

**Comment by wendyhuang2021** [comment]
Yes! I used single GPU and similar code like you written. It remain 3.5 hr to finish the ADE20k 100-50 setting.
However, the author have produce error in this setting, and I cannot check if those edited harm the performance even finished above setting.
Maybe I would tried another setting later.

**Comment by qjadud1994** [comment]
If you use a single GPU, you should remove `.module.` due to the DDP wrapper.

Also, we are currently checking the ADE20K 100-50 setting.
